import { existsSync, readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { basename, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { homedir } from 'node:os';
import { execFileSync } from 'node:child_process';

export interface DiscoveredShell {
  name: string;
  argv: string[];
  env?: Record<string, string>;
}

const PWSH_CWD_HOOK = join(
  dirname(fileURLToPath(import.meta.url)),
  'shell-init',
  'pwsh-cwd-hook.ps1',
);

const PWSH_ARGS = [
  '-NoLogo',
  '-NoExit',
  '-ExecutionPolicy', 'Bypass',
  '-File', PWSH_CWD_HOOK,
];

const UNIX_FALLBACK_PATHS = [
  '/bin/bash',
  '/usr/bin/bash',
  '/bin/zsh',
  '/usr/bin/zsh',
  '/bin/sh',
  '/usr/bin/sh',
  '/usr/bin/fish',
  '/usr/local/bin/fish',
  '/bin/dash',
  '/usr/bin/dash',
  '/bin/ksh',
  '/usr/bin/ksh',
  '/bin/tcsh',
  '/usr/bin/tcsh',
];

const UNIX_LOGIN_SHELLS = new Set(['bash', 'zsh', 'fish', 'ksh', 'tcsh', 'dash']);

// ── POSIX cwd reporting (OSC 7) ─────────────────────────────────────────────
//
// mobitty sets TERM_PROGRAM=mobitty (docs/done-design-terminal-env.md). On macOS
// that suppresses the stock zsh cwd hook: /etc/zshrc only sources
// /etc/zshrc_$TERM_PROGRAM, and Apple ships the emitter as
// /etc/zshrc_Apple_Terminal. With no replacement, no OSC 7 is ever emitted and
// the session list falls back to an `lsof` probe per session — which used to
// block the event loop on every connect and session switch.
// See docs/done-bug-lsof-cwd-blocks-connect.md.
//
// zsh has no environment-variable equivalent of `precmd`, so we point ZDOTDIR at
// a generated shim directory whose stubs forward to the user's real startup
// files and then install the hook. bash is simpler: PROMPT_COMMAND is honoured
// straight from the environment.
//
// Both encode `%` and spaces so the OSC 7 payload survives the client's
// percent-decoding (osc-cwd.ts).

const ZDOTDIR_ZSHENV = `# Generated by mobitty — do not edit; regenerated on server start.
# ZDOTDIR points at this directory so mobitty can install an OSC 7 cwd hook.
# Every stub forwards to the user's real startup file first.
: \${MOBITTY_USER_ZDOTDIR:=$HOME}
_mobitty_shim=$ZDOTDIR
[ -r "$MOBITTY_USER_ZDOTDIR/.zshenv" ] && . "$MOBITTY_USER_ZDOTDIR/.zshenv"
# The user's .zshenv may itself set ZDOTDIR — honour it as the new "real" dir,
# but re-assert ours so the remaining stubs still load.
[ "$ZDOTDIR" != "$_mobitty_shim" ] && MOBITTY_USER_ZDOTDIR=$ZDOTDIR
ZDOTDIR=$_mobitty_shim
unset _mobitty_shim
`;

const ZDOTDIR_ZPROFILE = `# Generated by mobitty — do not edit.
[ -r "\${MOBITTY_USER_ZDOTDIR:-$HOME}/.zprofile" ] && . "\${MOBITTY_USER_ZDOTDIR:-$HOME}/.zprofile"
`;

const ZDOTDIR_ZSHRC = `# Generated by mobitty — do not edit.
[ -r "\${MOBITTY_USER_ZDOTDIR:-$HOME}/.zshrc" ] && . "\${MOBITTY_USER_ZDOTDIR:-$HOME}/.zshrc"

# Emit OSC 7 before each prompt so the session list tracks the cwd without
# mobitty having to shell out to lsof.
if autoload -Uz add-zsh-hook 2>/dev/null; then
  _mobitty_report_cwd() {
    emulate -L zsh
    local p=\${PWD//\\%/%25}
    printf '\\033]7;file://%s%s\\a' "\${HOST}" "\${p// /%20}"
  }
  add-zsh-hook precmd _mobitty_report_cwd
fi

# Hand ZDOTDIR back so anything later (.zlogin, user tooling) sees the real one.
ZDOTDIR="\${MOBITTY_USER_ZDOTDIR:-$HOME}"
`;

const BASH_PROMPT_COMMAND =
  '__mobitty_p=${PWD//%/%25}; printf "\\033]7;file://%s%s\\a" "$HOSTNAME" "${__mobitty_p// /%20}"';

/** Writes the zsh ZDOTDIR shim into `{dataFolder}/shell-init/zdotdir` and
 *  returns its path, or null if it could not be created. */
function ensureZshZdotdir(dataFolder: string): string | null {
  try {
    const dir = join(dataFolder, 'shell-init', 'zdotdir');
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, '.zshenv'), ZDOTDIR_ZSHENV);
    writeFileSync(join(dir, '.zprofile'), ZDOTDIR_ZPROFILE);
    writeFileSync(join(dir, '.zshrc'), ZDOTDIR_ZSHRC);
    // Deliberately no .zlogin: .zshrc restores ZDOTDIR, so zsh picks up the
    // user's own .zlogin from the real directory.
    return dir;
  } catch {
    return null;
  }
}

/** Per-shell env that makes the shell report its cwd via OSC 7. */
function shellEnvForUnix(name: string, dataFolder: string | undefined): Record<string, string> | undefined {
  if (name === 'zsh') {
    if (!dataFolder) return undefined;
    const dir = ensureZshZdotdir(dataFolder);
    if (!dir) return undefined;
    return {
      ZDOTDIR: dir,
      MOBITTY_USER_ZDOTDIR: process.env['ZDOTDIR'] ?? homedir(),
    };
  }
  if (name === 'bash') {
    // A user .bashrc that assigns PROMPT_COMMAND wins; we then fall back to the
    // (now async) lsof probe, which is correct, just slower.
    return { PROMPT_COMMAND: BASH_PROMPT_COMMAND };
  }
  // fish emits OSC 7 on its own; other shells fall back to getProcessCwd.
  return undefined;
}

function parseEtcShells(): string[] {
  try {
    const content = readFileSync('/etc/shells', 'utf-8');
    return content
      .split('\n')
      .map(line => line.trim())
      .filter(line => line.length > 0 && !line.startsWith('#'));
  } catch {
    return [];
  }
}

function shellArgsForUnix(name: string, path: string): string[] {
  if (UNIX_LOGIN_SHELLS.has(name)) {
    return [path, '-i', '-l'];
  }
  if (name === 'pwsh') {
    return [path, ...PWSH_ARGS];
  }
  return [path];
}

function discoverUnix(dataFolder?: string): DiscoveredShell[] {
  const seen = new Set<string>();
  const shells: DiscoveredShell[] = [];

  const paths = parseEtcShells();
  const candidates = paths.length > 0 ? paths : UNIX_FALLBACK_PATHS;

  for (const shellPath of candidates) {
    if (!existsSync(shellPath)) continue;
    const name = basename(shellPath);
    if (seen.has(name)) continue;
    seen.add(name);
    const env = shellEnvForUnix(name, dataFolder);
    const shell: DiscoveredShell = { name, argv: shellArgsForUnix(name, shellPath) };
    if (env) shell.env = env;
    shells.push(shell);
  }

  return shells;
}

function existsOnPath(cmd: string): boolean {
  try {
    execFileSync('where', [cmd], { stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}

interface WindowsCandidate {
  name: string;
  cmd: string;
  absolutePaths: string[];
  args: string[];
}

const WINDOWS_CANDIDATES: WindowsCandidate[] = [
  { name: 'powershell', cmd: 'powershell.exe', absolutePaths: [], args: PWSH_ARGS },
  {
    name: 'pwsh',
    cmd: 'pwsh.exe',
    absolutePaths: ['C:\\Program Files\\PowerShell\\7\\pwsh.exe'],
    args: PWSH_ARGS,
  },
  { name: 'cmd', cmd: 'cmd.exe', absolutePaths: [], args: [] },
  {
    name: 'git-bash',
    cmd: '',
    absolutePaths: [
      'C:\\Program Files\\Git\\bin\\bash.exe',
      'C:\\Program Files (x86)\\Git\\bin\\bash.exe',
    ],
    args: ['-i', '-l'],
  },
  { name: 'wsl', cmd: 'wsl.exe', absolutePaths: [], args: [] },
];

function discoverWindows(): DiscoveredShell[] {
  const shells: DiscoveredShell[] = [];

  for (const candidate of WINDOWS_CANDIDATES) {
    // Check absolute paths first
    let found = false;
    for (const absPath of candidate.absolutePaths) {
      if (existsSync(absPath)) {
        shells.push({ name: candidate.name, argv: [absPath, ...candidate.args] });
        found = true;
        break;
      }
    }
    if (found) continue;

    // Check PATH
    if (candidate.cmd && existsOnPath(candidate.cmd)) {
      shells.push({ name: candidate.name, argv: [candidate.cmd, ...candidate.args] });
    }
  }

  return shells;
}

export function discoverShells(dataFolder?: string): DiscoveredShell[] {
  if (process.platform === 'win32') {
    return discoverWindows();
  }
  return discoverUnix(dataFolder);
}
